Globals = {};
Globals.ForumTopicsSortEnum = {
  Default: 0,
  LastReplied: 1,
  MostReplied: 2,
  Popularity: 3,
  Controversiality: 4,
  Liked: 5,
  HighestRated: 6
};
Globals.ForumTopicsCategoryFiltersEnum = {
  None: 0,
  Links: 1,
  Questions: 2,
  AnsweredQuestions: 4,
  Media: 8,
  TextOnly: 16,
  Announcement: 32,
  BungieOfficial: 64,
  Polls: 128
};
Globals.ForumPostCategoryEnums = {
  None: 0,
  TextOnly: 1,
  Media: 2,
  Link: 4,
  Poll: 8,
  Question: 16,
  Answered: 32,
  Announcement: 64,
  ContentComment: 128,
  BungieOfficial: 256,
  NinjaOfficial: 512
};
Globals.ForumTopicsQuickDateEnum = {
  All: 0,
  LastYear: 1,
  LastMonth: 2,
  LastWeek: 3,
  LastDay: 4
};
Globals.NotificationType = {
  MESSAGE: 1,
  FORUM_REPLY: 2,
  NEW_ACTIVITY_ROLLUP: 3,
  SETTINGS_CHANGE: 4,
  GROUP_ACCEPTANCE: 5,
  GROUP_JOIN_REQUEST: 6,
  FOLLOW_USER_ACTIVITY: 7,
  FRIEND_USER_ACTIVITY: 8,
  FORUM_LIKE: 9,
  FOLLOWED: 10,
  GROUP_BANNED: 11,
  BANNED: 12,
  UNBANNED: 13,
  GROUP_OPEN_JOIN: 14,
  GROUP_ALLIANCE_JOIN_REQUESTED: 15,
  GROUP_ALLIANCE_JOIN_REJECTED: 16,
  GROUP_ALLIANCE_JOIN_APPROVED: 17,
  GROUP_ALLIANCE_BROKEN: 18,
  GROUP_DENIAL: 19,
  WARNED: 20,
  CLAN_DISABLED: 21,
  GROUP_ALLIANCE_INVITE_REQUESTED: 22,
  GROUP_ALLIANCE_INVITE_REJECTED: 23,
  GROUP_ALLIANCE_INVITE_APPROVED: 24,
  GROUP_FOLLOWED_BY_GROUP: 25,
  GRIMOIRE_UNOBSERVED_CARDS: 26
};
Globals.NotificationMethod = {
  EMAIL: 1,
  MOBILE_PUSH: 2,
  WEB_ONLY: 4
};
Globals.GroupDateRange = {
  All: 0,
  PastDay: 1,
  PastWeek: 2,
  PastMonth: 3,
  PastYear: 4
};
Globals.GroupSortBy = {
  Name: 0,
  Date: 1,
  Popularity: 2,
  Id: 3
};
Globals.GroupHomepage = {
  Wall: 0,
  Forum: 1,
  AllianceForum: 2
};
Globals.TextParameterSearchType = {
  Contains: 0,
  Exact: 1,
  StartsWith: 2,
  EndsWith: 3
};
Globals.IgnoredItemType = {
  All: 0,
  Post: 1,
  Group: 2,
  User: 3,
  Tag: 4
};
Globals.IgnoreLength = {
  None: 0,
  Week: 1,
  TwoWeeks: 2,
  ThreeWeeks: 3,
  Month: 4,
  ThreeMonths: 5,
  SixMonths: 6,
  Year: 7,
  Forever: 8,
  ThreeMinutes: 9,
  Hour: 10
};
Globals.BungieCredentialType = {
  None: 0,
  Xuid: 1,
  Psnid: 2,
  Wlid: 3,
  Fake: 4,
  Facebook: 5,
  Google: 8,
  Windows: 9,
  DemonId: 10
};
Globals.ActivityAggregationType = {
  None: 0,
  Activities: 1,
  Followers: 2
};
Globals.ActivityType = {
  Create: 0,
  Edit: 1,
  Delete: 2,
  Rate: 3,
  Follow: 4,
  Unfollow: 5,
  Apply: 6,
  Rescind: 7,
  Approve: 8,
  Deny: 9,
  Kick: 10,
  EditMembershipType: 11,
  Like: 12,
  Unlike: 13,
  Share: 14,
  TaggedGroup: 15,
  TaggedTopic: 16,
  AvatarChanged: 17,
  DisplayNameChanged: 18,
  TitleChanged: 19,
  TitleUnlocked: 20,
  GroupTopicCreate: 21,
  GroupReplyCreate: 22,
  Reply: 23,
  ChangeClanName: 24,
  GroupAllianceRejected: 26,
  GroupAllianceApproved: 27,
  GroupAllianceBroken: 28,
  None: -1
};
Globals.AffectedItemType = {
  User: 0,
  Post: 1,
  Topic: 2,
  Group: 3,
  Tag: 4,
  None: -1
};
Globals.ActivityStatus = {
  Processing: 0,
  Failed: 1,
  Skipped: 2,
  Complete: 3
};
Globals.ActivityItemOrigin = {
  FollowedGroup: 0,
  FollowedUser: 1,
  ActivitiesAboutMe: 2,
  MyActivities: 3,
  Undetermined: -1
};
Globals.ActivityQueryFilter = {
  All: 0,
  Friends: 1,
  Following: 2,
  Groups: 3,
  Mine: 4,
  Tags: 5,
  Clans: 6
};
Globals.ForumFlagsEnum = {
  None: 0,
  BungieStaffPost: 1,
  ForumNinjaPost: 2,
  ForumMentorPost: 4
};
Globals.AclEnum = {
  None: 0,
  BNextForumNinja: 1,
  BNextUnlimitedGroups: 2,
  BNextFounderInAllGroups: 3,
  BNextBungieGold: 4,
  BNextNinjaColors: 5,
  BNextMakeOfficialTopics: 6,
  BNextMakeNinjaTopics: 7,
  BNextDeleteForumTopics: 8,
  BNextOverturnReports: 9,
  BNextBrowseReports: 10,
  BNextGlobalIgnore: 11,
  BNextEditAnyPublicPost: 12,
  BNextEditUsers: 13,
  BNextUltraBan: 14,
  BNextForumMentor: 15
};
Globals.IgnoreStatus = {
  NotIgnored: 0,
  IgnoredUser: 1,
  IgnoredGroup: 2,
  IgnoredByGroup: 4,
  IgnoredPost: 8,
  IgnoredTag: 16,
  IgnoredGlobal: 32
};
Globals.ContentDateRange = {
  All: 0,
  Today: 1,
  Yesterday: 2,
  ThisMonth: 3,
  ThisYear: 4,
  LastYear: 5,
  EarlierThanLastYear: 6
};
Globals.ContentSortBy = {
  CreationDate: 0,
  CmsPath: 1
};
Globals.FriendOnlineStatus = {
  Offline: 0,
  Online: 1,
  Idle: 2
};
Globals.ForumPostPopularity = {
  Empty: 0,
  Default: 1,
  Discussed: 2,
  CoolStory: 3,
  HeatingUp: 4,
  Hot: 5
};
Globals.MembershipOption = {
  Reviewed: 0,
  Open: 1,
  Closed: 2
};
Globals.SuccessMessages = {
  Following: 1,
  Unfollowing: 2,
  ManagingGroupMembers: 8,
  UpdatingSettings: 16,
  ManagingGroups: 32
};
Globals.ExternalService = {
  None: 0,
  Twitter: 1,
  Facebook: 2,
  Youtube: 3,
  TwitterHelp: 4
};
Globals.ForumPostSortEnum = {
  Default: 0,
  OldestFirst: 1
};
Globals.SurveyCompletionFlags = {
  None: 0,
  UserResearchWebPageOne: 1,
  UserResearchWebPageTwo: 2
};
Globals.DestinyGender = {
  Male: 0,
  Female: 1,
  Unknown: 2
};
Globals.DestinyRace = {
  Human: 0,
  Awoken: 1,
  Exo: 2,
  Unknown: 3
};
Globals.DestinyClass = {
  Titan: 0,
  Hunter: 1,
  Warlock: 2,
  Unknown: 3
};
Globals.ItemBindStatus = {
  NotBound: 0,
  BoundToCharacter: 1,
  BoundToAccount: 2,
  BoundToGuild: 3
};
Globals.TierType = {
  Unknown: 0,
  Currency: 1,
  Basic: 2,
  Common: 3,
  Rare: 4,
  Superior: 5,
  Exotic: 6
};
Globals.GroupTypeSearchFilter = {
  All: 0,
  Group: 1,
  Clan: 2
};
Globals.GroupMemberCountFilter = {
  All: 0,
  OneToTen: 1,
  ElevenToOneHundred: 2,
  GreaterThanOneHundred: 3
};
Globals.PeriodType = {
  None: 0,
  Daily: 1,
  Monthly: 2,
  AllTime: 3,
  Activity: 4
};
Globals.DestinyStatsGroupType = {
  None: 0,
  General: 1,
  Weapons: 2,
  Medals: 3,
  Enemies: 4,
  ReservedGroups: 100,
  Leaderboard: 101,
  Activity: 102,
  UniqueWeapon: 103
};
Globals.DestinyActivityModeType = {
  None: 0,
  Story: 2,
  Strike: 3,
  Raid: 4,
  AllPvP: 5,
  Explore: 6,
  AllPvE: 7,
  PvPIntroduction: 8,
  ThreeVsThree: 9,
  Control: 10,
  Lockdown: 11,
  Team: 12,
  FreeForAll: 13
};
Globals.StatFeedbackState = {
  Good: 0,
  TooHigh: 1,
  TooLow: 2,
  WrongName: 4
};
Globals.RequestedPunishment = {
  Ban: 0,
  Warn: 1,
  BlastBan: 2
};
Globals.PlatformErrorCodes = {
  None: 0,
  Success: 1,
  TransportException: 2,
  UnhandledException: 3,
  NotImplemented: 4,
  SystemDisabled: 5,
  FailedToLoadAvailableLocalesConfiguration: 6,
  ParameterParseFailure: 7,
  ParameterInvalidRange: 8,
  BadRequest: 9,
  AuthenticationInvalid: 10,
  DataNotFound: 11,
  InsufficientPrivileges: 12,
  Duplicate: 13,
  UnknownSqlResult: 14,
  ValidationError: 15,
  ValidationMissingFieldError: 16,
  ValidationInvalidInputError: 17,
  InvalidParameters: 18,
  ParameterNotFound: 19,
  UnhandledHttpException: 20,
  NotFound: 21,
  WebAuthModuleAsyncFailed: 22,
  InvalidReturnValue: 23,
  UserBanned: 24,
  InvalidPostBody: 25,
  MissingPostBody: 26,
  ExternalServiceTimeout: 27,
  ValidationLengthError: 28,
  ValidationRangeError: 29,
  JsonDeserializationError: 30,
  ThrottleLimitExceeded: 31,
  ValidationTagError: 32,
  ValidationProfanityError: 33,
  ValidationUrlFormatError: 34,
  ThrottleLimitExceededMinutes: 35,
  ThrottleLimitExceededMomentarily: 36,
  ThrottleLimitExceededSeconds: 37,
  ExternalServiceUnknown: 38,
  ValidationWordLengthError: 39,
  ValidationInvisibleUnicode: 40,
  ValidationBadNames: 41,
  ExternalServiceFailed: 42,
  ServiceRetired: 43,
  UnknownSqlException: 44,
  UnsupportedLocale: 45,
  InvalidPageNumber: 46,
  MaximumPageSizeExceeded: 47,
  ServiceUnsupported: 48,
  UnableToUnPairMobileApp: 90,
  UnableToPairMobileApp: 91,
  CannotUseMobileAuthWithNonMobileProvider: 92,
  MissingDeviceCookie: 93,
  FacebookTokenExpired: 94,
  AuthTicketRequired: 95,
  CookieContextRequired: 96,
  UnknownAuthenticationError: 97,
  BungieNetAccountCreationRequired: 98,
  WebAuthRequired: 99,
  ContentUnknownSqlResult: 100,
  ContentNeedUniquePath: 101,
  ContentSqlException: 102,
  ContentNotFound: 103,
  ContentSuccessWithTagAddFail: 104,
  ContentSearchMissingParameters: 105,
  ContentInvalidId: 106,
  ContentPhysicalFileDeletionError: 107,
  ContentPhysicalFileCreationError: 108,
  ContentPerforceSubmissionError: 109,
  ContentPerforceInitializationError: 110,
  ContentDeploymentPackageNotReadyError: 111,
  ContentUploadFailed: 112,
  ContentTooManyResults: 113,
  ContentInvalidState: 115,
  ContentNavigationParentNotFound: 116,
  ContentNavigationParentUpdateError: 117,
  DeploymentPackageNotEditable: 118,
  ContentValidationError: 119,
  ContentPropertiesValidationError: 120,
  ContentTypeNotFound: 121,
  DeploymentPackageNotFound: 122,
  ContentSearchInvalidParameters: 123,
  ContentItemPropertyAggregationError: 124,
  DeploymentPackageFileNotFound: 125,
  ContentPerforceFileHistoryNotFound: 126,
  ContentAssetZipCreationFailure: 127,
  ContentAssetZipCreationBusy: 128,
  ContentProjectNotFound: 129,
  ContentFolderNotFound: 130,
  ContentPackagesInconsistent: 131,
  ContentPackagesInvalidState: 132,
  ContentPackagesInconsistentType: 133,
  ContentCannotDeletePackage: 134,
  ContentLockedForChanges: 135,
  ContentFileUploadFailed: 136,
  ContentNotReviewed: 137,
  ContentPermissionDenied: 138,
  ContentInvalidExternalUrl: 139,
  ContentExternalFileCannotBeImportedLocally: 140,
  ContentTagSaveFailure: 141,
  ContentPerforceUnmatchedFileError: 142,
  ContentPerforceChangelistResultNotFound: 143,
  ContentPerforceChangelistFileItemsNotFound: 144,
  ContentPerforceInvalidRevisionError: 145,
  ContentUnloadedSaveResult: 146,
  ContentPropertyInvalidNumber: 147,
  ContentPropertyInvalidUrl: 148,
  ContentPropertyInvalidDate: 149,
  ContentPropertyInvalidSet: 150,
  ContentPropertyCannotDeserialize: 151,
  ContentRegexValidationFailOnProperty: 152,
  ContentMaxLengthFailOnProperty: 153,
  ContentPropertyUnexpectedDeserializationError: 154,
  ContentPropertyRequired: 155,
  ContentCannotCreateFile: 156,
  ContentInvalidMigrationFile: 157,
  ContentMigrationAlteringProcessedItem: 158,
  ContentPropertyDefinitionNotFound: 159,
  ContentReviewDataChanged: 160,
  ContentRollbackRevisionNotInPackage: 161,
  ContentItemNotBasedOnLatestRevision: 162,
  ContentUnauthorized: 163,
  ContentCannotCreateDeploymentPackage: 164,
  ContentUserNotFound: 165,
  ContentLocalePermissionDenied: 166,
  ContentInvalidLinkToInternalEnvironment: 167,
  ContentInvalidBlacklistedContent: 168,
  UserNonUniqueName: 200,
  UserManualLinkingStepRequired: 201,
  UserCreateUnknownSqlResult: 202,
  UserCreateUnknownSqlException: 203,
  UserMalformedMembershipId: 204,
  UserCannotFindRequestedUser: 205,
  UserCannotLoadAccountCredentialLinkInfo: 206,
  UserInvalidMobileAppType: 207,
  UserMissingMobilePairingInfo: 208,
  UserCannotGenerateMobileKeyWhileUsingMobileCredential: 209,
  UserGenerateMobileKeyExistingSlotCollision: 210,
  UserDisplayNameMissingOrInvalid: 211,
  UserCannotLoadAccountProfileData: 212,
  UserCannotSaveUserProfileData: 213,
  UserEmailMissingOrInvalid: 214,
  UserTermsOfUseRequired: 215,
  UserCannotCreateNewAccountWhileLoggedIn: 216,
  UserCannotResolveCentralAccount: 217,
  UserInvalidAvatar: 218,
  UserMissingCreatedUserResult: 219,
  UserCannotChangeUniqueNameYet: 220,
  UserCannotChangeDisplayNameYet: 221,
  UserCannotChangeEmail: 222,
  UserUniqueNameMustStartWithLetter: 223,
  UserNoLinkedAccountsSupportFriendListings: 224,
  UserAcknowledgmentTableFull: 225,
  MessagingUnknownError: 300,
  MessagingSelfError: 301,
  MessagingSendThrottle: 302,
  MessagingNoBody: 303,
  MessagingTooManyUsers: 304,
  MessagingCanNotLeaveConversation: 305,
  MessagingUnableToSend: 306,
  MessagingDeletedUserForbidden: 307,
  MessagingCannotDeleteExternalConversation: 308,
  MessagingGroupChatDisabled: 309,
  MessagingMustIncludeSelfInPrivateMessage: 310,
  AddSurveyAnswersUnknownSqlException: 400,
  ForumBodyCannotBeEmpty: 500,
  ForumSubjectCannotBeEmptyOnTopicPost: 501,
  ForumCannotLocateParentPost: 502,
  ForumThreadLockedForReplies: 503,
  ForumUnknownSqlResultDuringCreatePost: 504,
  ForumUnknownTagCreationError: 505,
  ForumUnknownSqlResultDuringTagItem: 506,
  ForumUnknownExceptionCreatePost: 507,
  ForumQuestionMustBeTopicPost: 508,
  ForumExceptionDuringTagSearch: 509,
  ForumExceptionDuringTopicRetrieval: 510,
  ForumAliasedTagError: 511,
  ForumCannotLocateThread: 512,
  ForumUnknownExceptionEditPost: 513,
  ForumCannotLocatePost: 514,
  ForumUnknownExceptionGetOrCreateTags: 515,
  ForumEditPermissionDenied: 516,
  ForumUnknownSqlResultDuringTagIdRetrieval: 517,
  ForumCannotGetRating: 518,
  ForumUnknownExceptionGetRating: 519,
  ForumRatingsAccessError: 520,
  ForumRelatedPostAccessError: 521,
  ForumLatestReplyAccessError: 522,
  ForumUserStatusAccessError: 523,
  ForumAuthorAccessError: 524,
  ForumGroupAccessError: 525,
  ForumUrlExpectedButMissing: 526,
  ForumRepliesCannotBeEmpty: 527,
  ForumRepliesCannotBeInDifferentGroups: 528,
  ForumSubTopicCannotBeCreatedAtThisThreadLevel: 529,
  ForumCannotCreateContentTopic: 530,
  ForumTopicDoesNotExist: 531,
  ForumContentCommentsNotAllowed: 532,
  ForumUnknownSqlResultDuringEditPost: 533,
  ForumUnknownSqlResultDuringGetPost: 534,
  ForumPostValidationBadUrl: 535,
  ForumBodyTooLong: 536,
  ForumSubjectTooLong: 537,
  ForumAnnouncementNotAllowed: 538,
  ForumCannotShareOwnPost: 539,
  ForumEditNoOp: 540,
  ForumUnknownDatabaseErrorDuringGetPost: 541,
  ForumExceeedMaximumRowLimit: 542,
  ForumCannotSharePrivatePost: 543,
  ForumCannotCrossPostBetweenGroups: 544,
  ForumIncompatibleCategories: 555,
  ForumCannotUseTheseCategoriesOnNonTopicPost: 556,
  ForumCanOnlyDeleteTopics: 557,
  ForumDeleteSqlException: 558,
  ForumDeleteSqlUnknownResult: 559,
  ForumTooManyTags: 560,
  ForumCanOnlyRateTopics: 561,
  ForumBannedPostsCannotBeEdited: 562,
  ForumThreadRootIsBanned: 563,
  ForumCannotUseOfficialTagCategoryAsTag: 564,
  ForumAnswerCannotBeMadeOnCreatePost: 565,
  ForumAnswerCannotBeMadeOnEditPost: 566,
  ForumAnswerPostIdIsNotADirectReplyOfQuestion: 567,
  ForumAnswerTopicIdIsNotAQuestion: 568,
  ForumUnknownExceptionDuringMarkAnswer: 569,
  ForumUnknownSqlResultDuringMarkAnswer: 570,
  ForumCannotRateYourOwnPosts: 571,
  ForumPollsMustBeTheFirstPostInTopic: 572,
  ForumInvalidPollInput: 573,
  ForumGroupAdminEditNonMember: 574,
  ForumCannotEditModeratorEditedPost: 575,
  ForumRequiresDestinyMembership: 576,
  ForumUnexpectedError: 577,
  GroupMembershipApplicationAlreadyResolved: 601,
  GroupMembershipAlreadyApplied: 602,
  GroupMembershipInsufficientPrivileges: 603,
  GroupIdNotReturnedFromCreation: 604,
  GroupSearchInvalidParameters: 605,
  GroupMembershipPendingApplicationNotFound: 606,
  GroupInvalidId: 607,
  GroupInvalidMembershipId: 608,
  GroupInvalidMembershipType: 609,
  GroupMissingTags: 610,
  GroupMembershipNotFound: 611,
  GroupInvalidRating: 612,
  GroupUserFollowingAccessError: 613,
  GroupUserMembershipAccessError: 614,
  GroupCreatorAccessError: 615,
  GroupAdminAccessError: 616,
  GroupPrivatePostNotViewable: 617,
  GroupMembershipNotLoggedIn: 618,
  GroupNotDeleted: 619,
  GroupUnknownErrorUndeletingGroup: 620,
  GroupDeleted: 621,
  GroupNotFound: 622,
  GroupMemberBanned: 623,
  GroupMembershipClosed: 624,
  GroupPrivatePostOverrideError: 625,
  GroupNameTaken: 626,
  GroupDeletionGracePeriodExpired: 627,
  GroupCannotCheckBanStatus: 628,
  GroupMaximumMembershipCountReached: 629,
  NoDestinyAccountForClanPlatform: 630,
  AlreadyRequestingMembershipForClanPlatform: 631,
  AlreadyClanMemberOnPlatform: 632,
  GroupJoinedCannotSetClanName: 633,
  GroupLeftCannotClearClanName: 634,
  GroupRelationshipRequestPending: 635,
  GroupRelationshipRequestBlocked: 636,
  GroupRelationshipRequestNotFound: 637,
  GroupRelationshipBlockNotFound: 638,
  GroupRelationshipNotFound: 639,
  GroupAlreadyAllied: 641,
  GroupAlreadyMember: 642,
  GroupRelationshipAlreadyExists: 643,
  InvalidGroupTypesForRelationshipRequest: 644,
  GroupAtMaximumAlliances: 646,
  GroupCannotSetClanOnlySettings: 647,
  ClanCannotSetTwoDefaultPostTypes: 648,
  GroupMemberInvalidMemberType: 649,
  GroupInvalidPlatformType: 650,
  GroupMemberInvalidSort: 651,
  GroupInvalidResolveState: 652,
  ClanAlreadyEnabledForPlatform: 653,
  ClanNotEnabledForPlatform: 654,
  ClanEnabledButCouldNotJoinNoAccount: 655,
  ClanEnabledButCouldNotJoinAlreadyMember: 656,
  ClanCannotJoinNoCredential: 657,
  NoClanMembershipForPlatform: 658,
  GroupToGroupFollowLimitReached: 659,
  ChildGroupAlreadyInAlliance: 660,
  OwnerGroupAlreadyInAlliance: 661,
  AllianceOwnerCannotJoinAlliance: 662,
  GroupNotInAlliance: 663,
  ChildGroupCannotInviteToAlliance: 664,
  GroupToGroupAlreadyFollowed: 665,
  GroupToGroupNotFollowing: 666,
  ClanMaximumMembershipReached: 667,
  ClanNameNotValid: 668,
  ClanNameNotValidError: 669,
  AllianceOwnerNotDefined: 670,
  AllianceChildNotDefined: 671,
  ActivitiesUnknownException: 701,
  ActivitiesParameterNull: 702,
  ActivityCountsDiabled: 703,
  ActivitySearchInvalidParameters: 704,
  ActivityPermissionDenied: 705,
  ShareAlreadyShared: 706,
  ActivityLoggingDisabled: 707,
  ItemAlreadyFollowed: 801,
  ItemNotFollowed: 802,
  CannotFollowSelf: 803,
  GroupFollowLimitExceeded: 804,
  TagFollowLimitExceeded: 805,
  UserFollowLimitExceeded: 806,
  NoValidTagsInList: 900,
  BelowMinimumSuggestionLength: 901,
  CannotGetSuggestionsOnMultipleTagsSimultaneously: 902,
  NotAValidPartialTag: 903,
  TagSuggestionsUnknownSqlResult: 904,
  TagsUnableToLoadPopularTagsFromDatabase: 905,
  TagInvalid: 906,
  TagNotFound: 907,
  SingleTagExpected: 908,
  IgnoreInvalidParameters: 1e3,
  IgnoreSqlException: 1001,
  IgnoreErrorRetrievingGroupPermissions: 1002,
  IgnoreErrorInsufficientPermission: 1003,
  IgnoreErrorRetrievingItem: 1004,
  IgnoreCannotIgnoreSelf: 1005,
  IgnoreIllegalType: 1006,
  IgnoreNotFound: 1007,
  IgnoreUserGloballyIgnored: 1008,
  IgnoreUserIgnored: 1009,
  NotificationSettingInvalid: 1100,
  PSNExExpiredTicket: 1204,
  PSNExForbidden: 1205,
  PSNExSystemDisabled: 1218,
  PSNFriendsMissingTicket: 1219,
  PsnApiErrorCodeUnknown: 1223,
  PsnApiErrorWebException: 1224,
  PsnApiBadRequest: 1225,
  PsnApiAccessTokenRequired: 1226,
  PsnApiInvalidAccessToken: 1227,
  PsnApiExpiredAccessToken: 1228,
  PsnApiBannedUser: 1229,
  PsnApiAccountUpgradeRequired: 1230,
  PsnApiServiceTemporarilyUnavailable: 1231,
  PsnApiServerBusy: 1232,
  PsnApiUnderMaintenance: 1233,
  PsnApiProfileUserNotFound: 1234,
  PsnApiProfilePrivacyRestriction: 1235,
  PsnApiProfileUnderMaintenance: 1236,
  PsnApiAccountAttributeMissing: 1237,
  XblExSystemDisabled: 1300,
  XblExUnknownError: 1301,
  ReportNotYetResolved: 1400,
  ReportOverturnDoesNotChangeDecision: 1401,
  ReportNotFound: 1402,
  ReportAlreadyReported: 1403,
  ReportInvalidResolution: 1404,
  LegacyGameStatsSystemDisabled: 1500,
  LegacyGameStatsUnknownError: 1501,
  LegacyGameStatsMalformedSneakerNetCode: 1502,
  DestinyAccountAcquisitionFailure: 1600,
  DestinyAccountNotFound: 1601,
  DestinyBuildStatsDatabaseError: 1602,
  DestinyCharacterStatsDatabaseError: 1603,
  DestinyPvPStatsDatabaseError: 1604,
  DestinyPvEStatsDatabaseError: 1605,
  DestinyGrimoireStatsDatabaseError: 1606,
  DestinyStatsParameterMembershipTypeParseError: 1607,
  DestinyStatsParameterMembershipIdParseError: 1608,
  DestinyStatsParameterRangeParseError: 1609,
  DestinyStringItemHashNotFound: 1610,
  DestinyStringSetNotFound: 1611,
  DestinyContentLookupNotFoundForKey: 1612,
  DestinyContentItemNotFound: 1613,
  DestinyContentSectionNotFound: 1614,
  DestinyContentPropertyNotFound: 1615,
  DestinyContentConfigNotFound: 1616,
  DestinyContentPropertyBucketValueNotFound: 1617,
  DestinyUnexpectedError: 1618,
  DestinyInvalidAction: 1619,
  DestinyCharacterNotFound: 1620,
  DestinyInvalidFlag: 1621,
  DestinyInvalidRequest: 1622,
  DestinyItemNotFound: 1623,
  DestinyInvalidCustomizationChoices: 1624,
  DestinyVendorItemNotFound: 1625,
  DestinyInternalError: 1626,
  DestinyVendorNotFound: 1627,
  DestinyRecentActivitiesDatabaseError: 1628,
  DestinyItemBucketNotFound: 1629,
  DestinyInvalidMembershipType: 1630,
  DestinyVersionIncompatibility: 1631,
  DestinyItemAlreadyInInventory: 1632,
  DestinyBucketNotFound: 1633,
  DestinyCharacterNotInTower: 1634,
  DestinyCharacterNotLoggedIn: 1635,
  DestinyDefinitionsNotLoaded: 1636,
  DestinyInventoryFull: 1637,
  DestinyItemFailedLevelCheck: 1638,
  DestinyItemFailedUnlockCheck: 1639,
  DestinyItemUnequippable: 1640,
  DestinyItemUniqueEquipRestricted: 1641,
  DestinyNoRoomInDestination: 1642,
  DestinyServiceFailure: 1643,
  DestinyServiceRetired: 1644,
  DestinyTransferFailed: 1645,
  DestinyTransferNotFoundForSourceBucket: 1646,
  DestinyUnexpectedResultInVendorTransferCheck: 1647,
  DestinyUniquenessViolation: 1648,
  DestinyErrorDeserializationFailure: 1649,
  DestinyValidAccountTicketRequired: 1650,
  DestinyShardRelayClientTimeout: 1651,
  DestinyShardRelayProxyTimeout: 1652,
  FbInvalidRequest: 1800,
  FbRedirectMismatch: 1801,
  FbAccessDenied: 1802,
  FbUnsupportedResponseType: 1803,
  FbInvalidScope: 1804,
  FbUnsupportedGrantType: 1805,
  FbInvalidGrant: 1806,
  InvitationExpired: 1900,
  InvitationUnknownType: 1901,
  InvitationInvalidResponseStatus: 1902,
  InvitationInvalidType: 1903,
  InvitationAlreadyPending: 1904,
  InvitationInsufficientPermission: 1905,
  InvitationInvalidCode: 1906,
  InvitationInvalidTargetState: 1907,
  InvitationCannotBeReactivated: 1908,
  InvitationAutoApproved: 1909,
  InvitationNoRecipients: 1910,
  InvitationGroupCannotSendToSelf: 1911,
  InvitationTooManyRecipients: 1912,
  InvitationInvalid: 1913,
  InvitationNotFound: 1914,
  TokenInvalid: 2e3,
  TokenBadFormat: 2001,
  TokenAlreadyClaimed: 2002,
  TokenAlreadyClaimedSelf: 2003,
  TokenThrottling: 2004,
  TokenUnknownRedemptionFailure: 2005,
  TokenPurchaseClaimFailedAfterTokenClaimed: 2006,
  TokenUserAlreadyOwnsOffer: 2007,
  TokenInvalidOfferKey: 2008,
  TokenEmailNotValidated: 2009,
  TokenProvisioningBadVendorOrOffer: 2010,
  TokenPurchaseHistoryUnknownError: 2011,
  TokenThrottleStateUnknownError: 2012,
  TokenUserAgeNotVerified: 2013,
  TokenExceededOfferMaximum: 2014,
  TokenNoAvailableUnlocks: 2015,
  TokenMarketplaceInvalidPlatform: 2016,
  TokenNoMarketplaceCodesFound: 2017,
  TokenOfferNotAvailableForRedemption: 2018,
  TokenUnlockPartialFailure: 2019,
  TokenMarketplaceInvalidRegion: 2020
};
Globals.BucketCategory = {
  Invisible: 0,
  Item: 1,
  Currency: 2,
  Equippable: 3,
  Ignored: 4
};
Globals.BungieMembershipType = {
  None: 0,
  TigerXbox: 1,
  TigerPsn: 2,
  TigerDemon: 10,
  BungieNext: 254,
  All: -1
};
Globals.ReportResolutionStatus = {
  Unresolved: 0,
  Innocent: 1,
  GuiltyBan: 2,
  GuiltyBlastBan: 3,
  GuiltyWarn: 4,
  GuiltyAlias: 5
};
Globals.ForumTypeEnum = {
  Public: 0,
  News: 1,
  Group: 2,
  Alliance: 3
};
Globals.DamageType = {
  None: 0,
  Kinetic: 1,
  Arc: 2,
  Thermal: 3,
  Void: 4,
  Raid: 5
};
Globals.DestinyTalentNodeState = {
  Invalid: 0,
  CanUpgrade: 1,
  NoPoints: 2,
  NoPrerequisites: 3,
  NoSteps: 4,
  NoUnlock: 5,
  NoMaterial: 6,
  NoGridLevel: 7,
  SwappingLocked: 8,
  MustSwap: 9,
  Complete: 10,
  Unknown: 11
};
Globals.OfferRedeemMode = {
  Off: 0,
  Unlock: 1,
  Platform: 2
};
Globals.ClientDeviceType = {
  Unknown: 0,
  Xbox360: 1,
  Playstation3: 2,
  AndroidPhone: 3,
  AndroidTablet: 4,
  ApplePhone: 5,
  AppleTablet: 6,
  WebBrowser: 7,
  NativeWindows: 8,
  NativeMac: 9,
  WindowsPhone: 10,
  WindowsTablet: 11,
  XboxOne: 12,
  Playstation4: 13,
  Fake: 255
};
Globals.OptInFlags = {
  Newsletter: 1,
  System: 2,
  Marketing: 4,
  UserResearch: 8,
  CustomerService: 16
};
Globals.EquipFailureReason = {
  None: 0,
  ItemUnequippable: 1,
  ItemUniqueEquipRestricted: 2,
  ItemFailedUnlockCheck: 4,
  ItemFailedLevelCheck: 8,
  ItemNotOnCharacter: 16
};
Globals.UnitType = {
  None: 0,
  Count: 1,
  PerGame: 2,
  Seconds: 3,
  Points: 4,
  Team: 5,
  Distance: 6,
  Percent: 7,
  Ratio: 8,
  Boolean: 9,
  WeaponType: 10
};
Globals.EntityType = {
  None: 0,
  User: 1,
  Group: 2,
  Post: 3,
  Invitation: 4,
  Report: 5,
  Activity: 6,
  Conversation: 7
};
Globals.InvitationResponseState = {
  Unreviewed: 0,
  Approved: 1,
  Rejected: 2
};
ReverseGlobals = {};
ReverseGlobals.ForumTopicsSortEnum = {
  "0": "Default",
  "1": "LastReplied",
  "2": "MostReplied",
  "3": "Popularity",
  "4": "Controversiality",
  "5": "Liked",
  "6": "HighestRated"
};
ReverseGlobals.ForumTopicsCategoryFiltersEnum = {
  "0": "None",
  "1": "Links",
  "2": "Questions",
  "4": "AnsweredQuestions",
  "8": "Media",
  "16": "TextOnly",
  "32": "Announcement",
  "64": "BungieOfficial",
  "128": "Polls"
};
ReverseGlobals.ForumPostCategoryEnums = {
  "0": "None",
  "1": "TextOnly",
  "2": "Media",
  "4": "Link",
  "8": "Poll",
  "16": "Question",
  "32": "Answered",
  "64": "Announcement",
  "128": "ContentComment",
  "256": "BungieOfficial",
  "512": "NinjaOfficial"
};
ReverseGlobals.ForumTopicsQuickDateEnum = {
  "0": "All",
  "1": "LastYear",
  "2": "LastMonth",
  "3": "LastWeek",
  "4": "LastDay"
};
ReverseGlobals.NotificationType = {
  "1": "MESSAGE",
  "2": "FORUM_REPLY",
  "3": "NEW_ACTIVITY_ROLLUP",
  "4": "SETTINGS_CHANGE",
  "5": "GROUP_ACCEPTANCE",
  "6": "GROUP_JOIN_REQUEST",
  "7": "FOLLOW_USER_ACTIVITY",
  "8": "FRIEND_USER_ACTIVITY",
  "9": "FORUM_LIKE",
  "10": "FOLLOWED",
  "11": "GROUP_BANNED",
  "12": "BANNED",
  "13": "UNBANNED",
  "14": "GROUP_OPEN_JOIN",
  "15": "GROUP_ALLIANCE_JOIN_REQUESTED",
  "16": "GROUP_ALLIANCE_JOIN_REJECTED",
  "17": "GROUP_ALLIANCE_JOIN_APPROVED",
  "18": "GROUP_ALLIANCE_BROKEN",
  "19": "GROUP_DENIAL",
  "20": "WARNED",
  "21": "CLAN_DISABLED",
  "22": "GROUP_ALLIANCE_INVITE_REQUESTED",
  "23": "GROUP_ALLIANCE_INVITE_REJECTED",
  "24": "GROUP_ALLIANCE_INVITE_APPROVED",
  "25": "GROUP_FOLLOWED_BY_GROUP",
  "26": "GRIMOIRE_UNOBSERVED_CARDS"
};
ReverseGlobals.NotificationMethod = {
  "1": "EMAIL",
  "2": "MOBILE_PUSH",
  "4": "WEB_ONLY"
};
ReverseGlobals.GroupDateRange = {
  "0": "All",
  "1": "PastDay",
  "2": "PastWeek",
  "3": "PastMonth",
  "4": "PastYear"
};
ReverseGlobals.GroupSortBy = {
  "0": "Name",
  "1": "Date",
  "2": "Popularity",
  "3": "Id"
};
ReverseGlobals.GroupHomepage = {
  "0": "Wall",
  "1": "Forum",
  "2": "AllianceForum"
};
ReverseGlobals.TextParameterSearchType = {
  "0": "Contains",
  "1": "Exact",
  "2": "StartsWith",
  "3": "EndsWith"
};
ReverseGlobals.IgnoredItemType = {
  "0": "All",
  "1": "Post",
  "2": "Group",
  "3": "User",
  "4": "Tag"
};
ReverseGlobals.IgnoreLength = {
  "0": "None",
  "1": "Week",
  "2": "TwoWeeks",
  "3": "ThreeWeeks",
  "4": "Month",
  "5": "ThreeMonths",
  "6": "SixMonths",
  "7": "Year",
  "8": "Forever",
  "9": "ThreeMinutes",
  "10": "Hour"
};
ReverseGlobals.BungieCredentialType = {
  "0": "None",
  "1": "Xuid",
  "2": "Psnid",
  "3": "Wlid",
  "4": "Fake",
  "5": "Facebook",
  "8": "Google",
  "9": "Windows",
  "10": "DemonId"
};
ReverseGlobals.ActivityAggregationType = {
  "0": "None",
  "1": "Activities",
  "2": "Followers"
};
ReverseGlobals.ActivityType = {
  "0": "Create",
  "1": "Edit",
  "2": "Delete",
  "3": "Rate",
  "4": "Follow",
  "5": "Unfollow",
  "6": "Apply",
  "7": "Rescind",
  "8": "Approve",
  "9": "Deny",
  "10": "Kick",
  "11": "EditMembershipType",
  "12": "Like",
  "13": "Unlike",
  "14": "Share",
  "15": "TaggedGroup",
  "16": "TaggedTopic",
  "17": "AvatarChanged",
  "18": "DisplayNameChanged",
  "19": "TitleChanged",
  "20": "TitleUnlocked",
  "21": "GroupTopicCreate",
  "22": "GroupReplyCreate",
  "23": "Reply",
  "24": "ChangeClanName",
  "26": "GroupAllianceRejected",
  "27": "GroupAllianceApproved",
  "28": "GroupAllianceBroken",
  "-1": "None"
};
ReverseGlobals.AffectedItemType = {
  "0": "User",
  "1": "Post",
  "2": "Topic",
  "3": "Group",
  "4": "Tag",
  "-1": "None"
};
ReverseGlobals.ActivityStatus = {
  "0": "Processing",
  "1": "Failed",
  "2": "Skipped",
  "3": "Complete"
};
ReverseGlobals.ActivityItemOrigin = {
  "0": "FollowedGroup",
  "1": "FollowedUser",
  "2": "ActivitiesAboutMe",
  "3": "MyActivities",
  "-1": "Undetermined"
};
ReverseGlobals.ActivityQueryFilter = {
  "0": "All",
  "1": "Friends",
  "2": "Following",
  "3": "Groups",
  "4": "Mine",
  "5": "Tags",
  "6": "Clans"
};
ReverseGlobals.ForumFlagsEnum = {
  "0": "None",
  "1": "BungieStaffPost",
  "2": "ForumNinjaPost",
  "4": "ForumMentorPost"
};
ReverseGlobals.AclEnum = {
  "0": "None",
  "1": "BNextForumNinja",
  "2": "BNextUnlimitedGroups",
  "3": "BNextFounderInAllGroups",
  "4": "BNextBungieGold",
  "5": "BNextNinjaColors",
  "6": "BNextMakeOfficialTopics",
  "7": "BNextMakeNinjaTopics",
  "8": "BNextDeleteForumTopics",
  "9": "BNextOverturnReports",
  "10": "BNextBrowseReports",
  "11": "BNextGlobalIgnore",
  "12": "BNextEditAnyPublicPost",
  "13": "BNextEditUsers",
  "14": "BNextUltraBan",
  "15": "BNextForumMentor"
};
ReverseGlobals.IgnoreStatus = {
  "0": "NotIgnored",
  "1": "IgnoredUser",
  "2": "IgnoredGroup",
  "4": "IgnoredByGroup",
  "8": "IgnoredPost",
  "16": "IgnoredTag",
  "32": "IgnoredGlobal"
};
ReverseGlobals.ContentDateRange = {
  "0": "All",
  "1": "Today",
  "2": "Yesterday",
  "3": "ThisMonth",
  "4": "ThisYear",
  "5": "LastYear",
  "6": "EarlierThanLastYear"
};
ReverseGlobals.ContentSortBy = {
  "0": "CreationDate",
  "1": "CmsPath"
};
ReverseGlobals.FriendOnlineStatus = {
  "0": "Offline",
  "1": "Online",
  "2": "Idle"
};
ReverseGlobals.ForumPostPopularity = {
  "0": "Empty",
  "1": "Default",
  "2": "Discussed",
  "3": "CoolStory",
  "4": "HeatingUp",
  "5": "Hot"
};
ReverseGlobals.MembershipOption = {
  "0": "Reviewed",
  "1": "Open",
  "2": "Closed"
};
ReverseGlobals.SuccessMessages = {
  "1": "Following",
  "2": "Unfollowing",
  "8": "ManagingGroupMembers",
  "16": "UpdatingSettings",
  "32": "ManagingGroups"
};
ReverseGlobals.ExternalService = {
  "0": "None",
  "1": "Twitter",
  "2": "Facebook",
  "3": "Youtube",
  "4": "TwitterHelp"
};
ReverseGlobals.ForumPostSortEnum = {
  "0": "Default",
  "1": "OldestFirst"
};
ReverseGlobals.SurveyCompletionFlags = {
  "0": "None",
  "1": "UserResearchWebPageOne",
  "2": "UserResearchWebPageTwo"
};
ReverseGlobals.DestinyGender = {
  "0": "Male",
  "1": "Female",
  "2": "Unknown"
};
ReverseGlobals.DestinyRace = {
  "0": "Human",
  "1": "Awoken",
  "2": "Exo",
  "3": "Unknown"
};
ReverseGlobals.DestinyClass = {
  "0": "Titan",
  "1": "Hunter",
  "2": "Warlock",
  "3": "Unknown"
};
ReverseGlobals.ItemBindStatus = {
  "0": "NotBound",
  "1": "BoundToCharacter",
  "2": "BoundToAccount",
  "3": "BoundToGuild"
};
ReverseGlobals.TierType = {
  "0": "Unknown",
  "1": "Currency",
  "2": "Basic",
  "3": "Common",
  "4": "Rare",
  "5": "Superior",
  "6": "Exotic"
};
ReverseGlobals.GroupTypeSearchFilter = {
  "0": "All",
  "1": "Group",
  "2": "Clan"
};
ReverseGlobals.GroupMemberCountFilter = {
  "0": "All",
  "1": "OneToTen",
  "2": "ElevenToOneHundred",
  "3": "GreaterThanOneHundred"
};
ReverseGlobals.PeriodType = {
  "0": "None",
  "1": "Daily",
  "2": "Monthly",
  "3": "AllTime",
  "4": "Activity"
};
ReverseGlobals.DestinyStatsGroupType = {
  "0": "None",
  "1": "General",
  "2": "Weapons",
  "3": "Medals",
  "4": "Enemies",
  "100": "ReservedGroups",
  "101": "Leaderboard",
  "102": "Activity",
  "103": "UniqueWeapon"
};
ReverseGlobals.DestinyActivityModeType = {
  "0": "None",
  "2": "Story",
  "3": "Strike",
  "4": "Raid",
  "5": "AllPvP",
  "6": "Explore",
  "7": "AllPvE",
  "8": "PvPIntroduction",
  "9": "ThreeVsThree",
  "10": "Control",
  "11": "Lockdown",
  "12": "Team",
  "13": "FreeForAll"
};
ReverseGlobals.StatFeedbackState = {
  "0": "Good",
  "1": "TooHigh",
  "2": "TooLow",
  "4": "WrongName"
};
ReverseGlobals.RequestedPunishment = {
  "0": "Ban",
  "1": "Warn",
  "2": "BlastBan"
};
ReverseGlobals.PlatformErrorCodes = {
  "0": "None",
  "1": "Success",
  "2": "TransportException",
  "3": "UnhandledException",
  "4": "NotImplemented",
  "5": "SystemDisabled",
  "6": "FailedToLoadAvailableLocalesConfiguration",
  "7": "ParameterParseFailure",
  "8": "ParameterInvalidRange",
  "9": "BadRequest",
  "10": "AuthenticationInvalid",
  "11": "DataNotFound",
  "12": "InsufficientPrivileges",
  "13": "Duplicate",
  "14": "UnknownSqlResult",
  "15": "ValidationError",
  "16": "ValidationMissingFieldError",
  "17": "ValidationInvalidInputError",
  "18": "InvalidParameters",
  "19": "ParameterNotFound",
  "20": "UnhandledHttpException",
  "21": "NotFound",
  "22": "WebAuthModuleAsyncFailed",
  "23": "InvalidReturnValue",
  "24": "UserBanned",
  "25": "InvalidPostBody",
  "26": "MissingPostBody",
  "27": "ExternalServiceTimeout",
  "28": "ValidationLengthError",
  "29": "ValidationRangeError",
  "30": "JsonDeserializationError",
  "31": "ThrottleLimitExceeded",
  "32": "ValidationTagError",
  "33": "ValidationProfanityError",
  "34": "ValidationUrlFormatError",
  "35": "ThrottleLimitExceededMinutes",
  "36": "ThrottleLimitExceededMomentarily",
  "37": "ThrottleLimitExceededSeconds",
  "38": "ExternalServiceUnknown",
  "39": "ValidationWordLengthError",
  "40": "ValidationInvisibleUnicode",
  "41": "ValidationBadNames",
  "42": "ExternalServiceFailed",
  "43": "ServiceRetired",
  "44": "UnknownSqlException",
  "45": "UnsupportedLocale",
  "46": "InvalidPageNumber",
  "47": "MaximumPageSizeExceeded",
  "48": "ServiceUnsupported",
  "90": "UnableToUnPairMobileApp",
  "91": "UnableToPairMobileApp",
  "92": "CannotUseMobileAuthWithNonMobileProvider",
  "93": "MissingDeviceCookie",
  "94": "FacebookTokenExpired",
  "95": "AuthTicketRequired",
  "96": "CookieContextRequired",
  "97": "UnknownAuthenticationError",
  "98": "BungieNetAccountCreationRequired",
  "99": "WebAuthRequired",
  "100": "ContentUnknownSqlResult",
  "101": "ContentNeedUniquePath",
  "102": "ContentSqlException",
  "103": "ContentNotFound",
  "104": "ContentSuccessWithTagAddFail",
  "105": "ContentSearchMissingParameters",
  "106": "ContentInvalidId",
  "107": "ContentPhysicalFileDeletionError",
  "108": "ContentPhysicalFileCreationError",
  "109": "ContentPerforceSubmissionError",
  "110": "ContentPerforceInitializationError",
  "111": "ContentDeploymentPackageNotReadyError",
  "112": "ContentUploadFailed",
  "113": "ContentTooManyResults",
  "115": "ContentInvalidState",
  "116": "ContentNavigationParentNotFound",
  "117": "ContentNavigationParentUpdateError",
  "118": "DeploymentPackageNotEditable",
  "119": "ContentValidationError",
  "120": "ContentPropertiesValidationError",
  "121": "ContentTypeNotFound",
  "122": "DeploymentPackageNotFound",
  "123": "ContentSearchInvalidParameters",
  "124": "ContentItemPropertyAggregationError",
  "125": "DeploymentPackageFileNotFound",
  "126": "ContentPerforceFileHistoryNotFound",
  "127": "ContentAssetZipCreationFailure",
  "128": "ContentAssetZipCreationBusy",
  "129": "ContentProjectNotFound",
  "130": "ContentFolderNotFound",
  "131": "ContentPackagesInconsistent",
  "132": "ContentPackagesInvalidState",
  "133": "ContentPackagesInconsistentType",
  "134": "ContentCannotDeletePackage",
  "135": "ContentLockedForChanges",
  "136": "ContentFileUploadFailed",
  "137": "ContentNotReviewed",
  "138": "ContentPermissionDenied",
  "139": "ContentInvalidExternalUrl",
  "140": "ContentExternalFileCannotBeImportedLocally",
  "141": "ContentTagSaveFailure",
  "142": "ContentPerforceUnmatchedFileError",
  "143": "ContentPerforceChangelistResultNotFound",
  "144": "ContentPerforceChangelistFileItemsNotFound",
  "145": "ContentPerforceInvalidRevisionError",
  "146": "ContentUnloadedSaveResult",
  "147": "ContentPropertyInvalidNumber",
  "148": "ContentPropertyInvalidUrl",
  "149": "ContentPropertyInvalidDate",
  "150": "ContentPropertyInvalidSet",
  "151": "ContentPropertyCannotDeserialize",
  "152": "ContentRegexValidationFailOnProperty",
  "153": "ContentMaxLengthFailOnProperty",
  "154": "ContentPropertyUnexpectedDeserializationError",
  "155": "ContentPropertyRequired",
  "156": "ContentCannotCreateFile",
  "157": "ContentInvalidMigrationFile",
  "158": "ContentMigrationAlteringProcessedItem",
  "159": "ContentPropertyDefinitionNotFound",
  "160": "ContentReviewDataChanged",
  "161": "ContentRollbackRevisionNotInPackage",
  "162": "ContentItemNotBasedOnLatestRevision",
  "163": "ContentUnauthorized",
  "164": "ContentCannotCreateDeploymentPackage",
  "165": "ContentUserNotFound",
  "166": "ContentLocalePermissionDenied",
  "167": "ContentInvalidLinkToInternalEnvironment",
  "168": "ContentInvalidBlacklistedContent",
  "200": "UserNonUniqueName",
  "201": "UserManualLinkingStepRequired",
  "202": "UserCreateUnknownSqlResult",
  "203": "UserCreateUnknownSqlException",
  "204": "UserMalformedMembershipId",
  "205": "UserCannotFindRequestedUser",
  "206": "UserCannotLoadAccountCredentialLinkInfo",
  "207": "UserInvalidMobileAppType",
  "208": "UserMissingMobilePairingInfo",
  "209": "UserCannotGenerateMobileKeyWhileUsingMobileCredential",
  "210": "UserGenerateMobileKeyExistingSlotCollision",
  "211": "UserDisplayNameMissingOrInvalid",
  "212": "UserCannotLoadAccountProfileData",
  "213": "UserCannotSaveUserProfileData",
  "214": "UserEmailMissingOrInvalid",
  "215": "UserTermsOfUseRequired",
  "216": "UserCannotCreateNewAccountWhileLoggedIn",
  "217": "UserCannotResolveCentralAccount",
  "218": "UserInvalidAvatar",
  "219": "UserMissingCreatedUserResult",
  "220": "UserCannotChangeUniqueNameYet",
  "221": "UserCannotChangeDisplayNameYet",
  "222": "UserCannotChangeEmail",
  "223": "UserUniqueNameMustStartWithLetter",
  "224": "UserNoLinkedAccountsSupportFriendListings",
  "225": "UserAcknowledgmentTableFull",
  "300": "MessagingUnknownError",
  "301": "MessagingSelfError",
  "302": "MessagingSendThrottle",
  "303": "MessagingNoBody",
  "304": "MessagingTooManyUsers",
  "305": "MessagingCanNotLeaveConversation",
  "306": "MessagingUnableToSend",
  "307": "MessagingDeletedUserForbidden",
  "308": "MessagingCannotDeleteExternalConversation",
  "309": "MessagingGroupChatDisabled",
  "310": "MessagingMustIncludeSelfInPrivateMessage",
  "400": "AddSurveyAnswersUnknownSqlException",
  "500": "ForumBodyCannotBeEmpty",
  "501": "ForumSubjectCannotBeEmptyOnTopicPost",
  "502": "ForumCannotLocateParentPost",
  "503": "ForumThreadLockedForReplies",
  "504": "ForumUnknownSqlResultDuringCreatePost",
  "505": "ForumUnknownTagCreationError",
  "506": "ForumUnknownSqlResultDuringTagItem",
  "507": "ForumUnknownExceptionCreatePost",
  "508": "ForumQuestionMustBeTopicPost",
  "509": "ForumExceptionDuringTagSearch",
  "510": "ForumExceptionDuringTopicRetrieval",
  "511": "ForumAliasedTagError",
  "512": "ForumCannotLocateThread",
  "513": "ForumUnknownExceptionEditPost",
  "514": "ForumCannotLocatePost",
  "515": "ForumUnknownExceptionGetOrCreateTags",
  "516": "ForumEditPermissionDenied",
  "517": "ForumUnknownSqlResultDuringTagIdRetrieval",
  "518": "ForumCannotGetRating",
  "519": "ForumUnknownExceptionGetRating",
  "520": "ForumRatingsAccessError",
  "521": "ForumRelatedPostAccessError",
  "522": "ForumLatestReplyAccessError",
  "523": "ForumUserStatusAccessError",
  "524": "ForumAuthorAccessError",
  "525": "ForumGroupAccessError",
  "526": "ForumUrlExpectedButMissing",
  "527": "ForumRepliesCannotBeEmpty",
  "528": "ForumRepliesCannotBeInDifferentGroups",
  "529": "ForumSubTopicCannotBeCreatedAtThisThreadLevel",
  "530": "ForumCannotCreateContentTopic",
  "531": "ForumTopicDoesNotExist",
  "532": "ForumContentCommentsNotAllowed",
  "533": "ForumUnknownSqlResultDuringEditPost",
  "534": "ForumUnknownSqlResultDuringGetPost",
  "535": "ForumPostValidationBadUrl",
  "536": "ForumBodyTooLong",
  "537": "ForumSubjectTooLong",
  "538": "ForumAnnouncementNotAllowed",
  "539": "ForumCannotShareOwnPost",
  "540": "ForumEditNoOp",
  "541": "ForumUnknownDatabaseErrorDuringGetPost",
  "542": "ForumExceeedMaximumRowLimit",
  "543": "ForumCannotSharePrivatePost",
  "544": "ForumCannotCrossPostBetweenGroups",
  "555": "ForumIncompatibleCategories",
  "556": "ForumCannotUseTheseCategoriesOnNonTopicPost",
  "557": "ForumCanOnlyDeleteTopics",
  "558": "ForumDeleteSqlException",
  "559": "ForumDeleteSqlUnknownResult",
  "560": "ForumTooManyTags",
  "561": "ForumCanOnlyRateTopics",
  "562": "ForumBannedPostsCannotBeEdited",
  "563": "ForumThreadRootIsBanned",
  "564": "ForumCannotUseOfficialTagCategoryAsTag",
  "565": "ForumAnswerCannotBeMadeOnCreatePost",
  "566": "ForumAnswerCannotBeMadeOnEditPost",
  "567": "ForumAnswerPostIdIsNotADirectReplyOfQuestion",
  "568": "ForumAnswerTopicIdIsNotAQuestion",
  "569": "ForumUnknownExceptionDuringMarkAnswer",
  "570": "ForumUnknownSqlResultDuringMarkAnswer",
  "571": "ForumCannotRateYourOwnPosts",
  "572": "ForumPollsMustBeTheFirstPostInTopic",
  "573": "ForumInvalidPollInput",
  "574": "ForumGroupAdminEditNonMember",
  "575": "ForumCannotEditModeratorEditedPost",
  "576": "ForumRequiresDestinyMembership",
  "577": "ForumUnexpectedError",
  "601": "GroupMembershipApplicationAlreadyResolved",
  "602": "GroupMembershipAlreadyApplied",
  "603": "GroupMembershipInsufficientPrivileges",
  "604": "GroupIdNotReturnedFromCreation",
  "605": "GroupSearchInvalidParameters",
  "606": "GroupMembershipPendingApplicationNotFound",
  "607": "GroupInvalidId",
  "608": "GroupInvalidMembershipId",
  "609": "GroupInvalidMembershipType",
  "610": "GroupMissingTags",
  "611": "GroupMembershipNotFound",
  "612": "GroupInvalidRating",
  "613": "GroupUserFollowingAccessError",
  "614": "GroupUserMembershipAccessError",
  "615": "GroupCreatorAccessError",
  "616": "GroupAdminAccessError",
  "617": "GroupPrivatePostNotViewable",
  "618": "GroupMembershipNotLoggedIn",
  "619": "GroupNotDeleted",
  "620": "GroupUnknownErrorUndeletingGroup",
  "621": "GroupDeleted",
  "622": "GroupNotFound",
  "623": "GroupMemberBanned",
  "624": "GroupMembershipClosed",
  "625": "GroupPrivatePostOverrideError",
  "626": "GroupNameTaken",
  "627": "GroupDeletionGracePeriodExpired",
  "628": "GroupCannotCheckBanStatus",
  "629": "GroupMaximumMembershipCountReached",
  "630": "NoDestinyAccountForClanPlatform",
  "631": "AlreadyRequestingMembershipForClanPlatform",
  "632": "AlreadyClanMemberOnPlatform",
  "633": "GroupJoinedCannotSetClanName",
  "634": "GroupLeftCannotClearClanName",
  "635": "GroupRelationshipRequestPending",
  "636": "GroupRelationshipRequestBlocked",
  "637": "GroupRelationshipRequestNotFound",
  "638": "GroupRelationshipBlockNotFound",
  "639": "GroupRelationshipNotFound",
  "641": "GroupAlreadyAllied",
  "642": "GroupAlreadyMember",
  "643": "GroupRelationshipAlreadyExists",
  "644": "InvalidGroupTypesForRelationshipRequest",
  "646": "GroupAtMaximumAlliances",
  "647": "GroupCannotSetClanOnlySettings",
  "648": "ClanCannotSetTwoDefaultPostTypes",
  "649": "GroupMemberInvalidMemberType",
  "650": "GroupInvalidPlatformType",
  "651": "GroupMemberInvalidSort",
  "652": "GroupInvalidResolveState",
  "653": "ClanAlreadyEnabledForPlatform",
  "654": "ClanNotEnabledForPlatform",
  "655": "ClanEnabledButCouldNotJoinNoAccount",
  "656": "ClanEnabledButCouldNotJoinAlreadyMember",
  "657": "ClanCannotJoinNoCredential",
  "658": "NoClanMembershipForPlatform",
  "659": "GroupToGroupFollowLimitReached",
  "660": "ChildGroupAlreadyInAlliance",
  "661": "OwnerGroupAlreadyInAlliance",
  "662": "AllianceOwnerCannotJoinAlliance",
  "663": "GroupNotInAlliance",
  "664": "ChildGroupCannotInviteToAlliance",
  "665": "GroupToGroupAlreadyFollowed",
  "666": "GroupToGroupNotFollowing",
  "667": "ClanMaximumMembershipReached",
  "668": "ClanNameNotValid",
  "669": "ClanNameNotValidError",
  "670": "AllianceOwnerNotDefined",
  "671": "AllianceChildNotDefined",
  "701": "ActivitiesUnknownException",
  "702": "ActivitiesParameterNull",
  "703": "ActivityCountsDiabled",
  "704": "ActivitySearchInvalidParameters",
  "705": "ActivityPermissionDenied",
  "706": "ShareAlreadyShared",
  "707": "ActivityLoggingDisabled",
  "801": "ItemAlreadyFollowed",
  "802": "ItemNotFollowed",
  "803": "CannotFollowSelf",
  "804": "GroupFollowLimitExceeded",
  "805": "TagFollowLimitExceeded",
  "806": "UserFollowLimitExceeded",
  "900": "NoValidTagsInList",
  "901": "BelowMinimumSuggestionLength",
  "902": "CannotGetSuggestionsOnMultipleTagsSimultaneously",
  "903": "NotAValidPartialTag",
  "904": "TagSuggestionsUnknownSqlResult",
  "905": "TagsUnableToLoadPopularTagsFromDatabase",
  "906": "TagInvalid",
  "907": "TagNotFound",
  "908": "SingleTagExpected",
  "1000": "IgnoreInvalidParameters",
  "1001": "IgnoreSqlException",
  "1002": "IgnoreErrorRetrievingGroupPermissions",
  "1003": "IgnoreErrorInsufficientPermission",
  "1004": "IgnoreErrorRetrievingItem",
  "1005": "IgnoreCannotIgnoreSelf",
  "1006": "IgnoreIllegalType",
  "1007": "IgnoreNotFound",
  "1008": "IgnoreUserGloballyIgnored",
  "1009": "IgnoreUserIgnored",
  "1100": "NotificationSettingInvalid",
  "1204": "PSNExExpiredTicket",
  "1205": "PSNExForbidden",
  "1218": "PSNExSystemDisabled",
  "1219": "PSNFriendsMissingTicket",
  "1223": "PsnApiErrorCodeUnknown",
  "1224": "PsnApiErrorWebException",
  "1225": "PsnApiBadRequest",
  "1226": "PsnApiAccessTokenRequired",
  "1227": "PsnApiInvalidAccessToken",
  "1228": "PsnApiExpiredAccessToken",
  "1229": "PsnApiBannedUser",
  "1230": "PsnApiAccountUpgradeRequired",
  "1231": "PsnApiServiceTemporarilyUnavailable",
  "1232": "PsnApiServerBusy",
  "1233": "PsnApiUnderMaintenance",
  "1234": "PsnApiProfileUserNotFound",
  "1235": "PsnApiProfilePrivacyRestriction",
  "1236": "PsnApiProfileUnderMaintenance",
  "1237": "PsnApiAccountAttributeMissing",
  "1300": "XblExSystemDisabled",
  "1301": "XblExUnknownError",
  "1400": "ReportNotYetResolved",
  "1401": "ReportOverturnDoesNotChangeDecision",
  "1402": "ReportNotFound",
  "1403": "ReportAlreadyReported",
  "1404": "ReportInvalidResolution",
  "1500": "LegacyGameStatsSystemDisabled",
  "1501": "LegacyGameStatsUnknownError",
  "1502": "LegacyGameStatsMalformedSneakerNetCode",
  "1600": "DestinyAccountAcquisitionFailure",
  "1601": "DestinyAccountNotFound",
  "1602": "DestinyBuildStatsDatabaseError",
  "1603": "DestinyCharacterStatsDatabaseError",
  "1604": "DestinyPvPStatsDatabaseError",
  "1605": "DestinyPvEStatsDatabaseError",
  "1606": "DestinyGrimoireStatsDatabaseError",
  "1607": "DestinyStatsParameterMembershipTypeParseError",
  "1608": "DestinyStatsParameterMembershipIdParseError",
  "1609": "DestinyStatsParameterRangeParseError",
  "1610": "DestinyStringItemHashNotFound",
  "1611": "DestinyStringSetNotFound",
  "1612": "DestinyContentLookupNotFoundForKey",
  "1613": "DestinyContentItemNotFound",
  "1614": "DestinyContentSectionNotFound",
  "1615": "DestinyContentPropertyNotFound",
  "1616": "DestinyContentConfigNotFound",
  "1617": "DestinyContentPropertyBucketValueNotFound",
  "1618": "DestinyUnexpectedError",
  "1619": "DestinyInvalidAction",
  "1620": "DestinyCharacterNotFound",
  "1621": "DestinyInvalidFlag",
  "1622": "DestinyInvalidRequest",
  "1623": "DestinyItemNotFound",
  "1624": "DestinyInvalidCustomizationChoices",
  "1625": "DestinyVendorItemNotFound",
  "1626": "DestinyInternalError",
  "1627": "DestinyVendorNotFound",
  "1628": "DestinyRecentActivitiesDatabaseError",
  "1629": "DestinyItemBucketNotFound",
  "1630": "DestinyInvalidMembershipType",
  "1631": "DestinyVersionIncompatibility",
  "1632": "DestinyItemAlreadyInInventory",
  "1633": "DestinyBucketNotFound",
  "1634": "DestinyCharacterNotInTower",
  "1635": "DestinyCharacterNotLoggedIn",
  "1636": "DestinyDefinitionsNotLoaded",
  "1637": "DestinyInventoryFull",
  "1638": "DestinyItemFailedLevelCheck",
  "1639": "DestinyItemFailedUnlockCheck",
  "1640": "DestinyItemUnequippable",
  "1641": "DestinyItemUniqueEquipRestricted",
  "1642": "DestinyNoRoomInDestination",
  "1643": "DestinyServiceFailure",
  "1644": "DestinyServiceRetired",
  "1645": "DestinyTransferFailed",
  "1646": "DestinyTransferNotFoundForSourceBucket",
  "1647": "DestinyUnexpectedResultInVendorTransferCheck",
  "1648": "DestinyUniquenessViolation",
  "1649": "DestinyErrorDeserializationFailure",
  "1650": "DestinyValidAccountTicketRequired",
  "1651": "DestinyShardRelayClientTimeout",
  "1652": "DestinyShardRelayProxyTimeout",
  "1800": "FbInvalidRequest",
  "1801": "FbRedirectMismatch",
  "1802": "FbAccessDenied",
  "1803": "FbUnsupportedResponseType",
  "1804": "FbInvalidScope",
  "1805": "FbUnsupportedGrantType",
  "1806": "FbInvalidGrant",
  "1900": "InvitationExpired",
  "1901": "InvitationUnknownType",
  "1902": "InvitationInvalidResponseStatus",
  "1903": "InvitationInvalidType",
  "1904": "InvitationAlreadyPending",
  "1905": "InvitationInsufficientPermission",
  "1906": "InvitationInvalidCode",
  "1907": "InvitationInvalidTargetState",
  "1908": "InvitationCannotBeReactivated",
  "1909": "InvitationAutoApproved",
  "1910": "InvitationNoRecipients",
  "1911": "InvitationGroupCannotSendToSelf",
  "1912": "InvitationTooManyRecipients",
  "1913": "InvitationInvalid",
  "1914": "InvitationNotFound",
  "2000": "TokenInvalid",
  "2001": "TokenBadFormat",
  "2002": "TokenAlreadyClaimed",
  "2003": "TokenAlreadyClaimedSelf",
  "2004": "TokenThrottling",
  "2005": "TokenUnknownRedemptionFailure",
  "2006": "TokenPurchaseClaimFailedAfterTokenClaimed",
  "2007": "TokenUserAlreadyOwnsOffer",
  "2008": "TokenInvalidOfferKey",
  "2009": "TokenEmailNotValidated",
  "2010": "TokenProvisioningBadVendorOrOffer",
  "2011": "TokenPurchaseHistoryUnknownError",
  "2012": "TokenThrottleStateUnknownError",
  "2013": "TokenUserAgeNotVerified",
  "2014": "TokenExceededOfferMaximum",
  "2015": "TokenNoAvailableUnlocks",
  "2016": "TokenMarketplaceInvalidPlatform",
  "2017": "TokenNoMarketplaceCodesFound",
  "2018": "TokenOfferNotAvailableForRedemption",
  "2019": "TokenUnlockPartialFailure",
  "2020": "TokenMarketplaceInvalidRegion"
};
ReverseGlobals.BucketCategory = {
  "0": "Invisible",
  "1": "Item",
  "2": "Currency",
  "3": "Equippable",
  "4": "Ignored"
};
ReverseGlobals.BungieMembershipType = {
  "0": "None",
  "1": "TigerXbox",
  "2": "TigerPsn",
  "10": "TigerDemon",
  "254": "BungieNext",
  "-1": "All"
};
ReverseGlobals.ReportResolutionStatus = {
  "0": "Unresolved",
  "1": "Innocent",
  "2": "GuiltyBan",
  "3": "GuiltyBlastBan",
  "4": "GuiltyWarn",
  "5": "GuiltyAlias"
};
ReverseGlobals.ForumTypeEnum = {
  "0": "Public",
  "1": "News",
  "2": "Group",
  "3": "Alliance"
};
ReverseGlobals.DamageType = {
  "0": "None",
  "1": "Kinetic",
  "2": "Arc",
  "3": "Thermal",
  "4": "Void",
  "5": "Raid"
};
ReverseGlobals.DestinyTalentNodeState = {
  "0": "Invalid",
  "1": "CanUpgrade",
  "2": "NoPoints",
  "3": "NoPrerequisites",
  "4": "NoSteps",
  "5": "NoUnlock",
  "6": "NoMaterial",
  "7": "NoGridLevel",
  "8": "SwappingLocked",
  "9": "MustSwap",
  "10": "Complete",
  "11": "Unknown"
};
ReverseGlobals.OfferRedeemMode = {
  "0": "Off",
  "1": "Unlock",
  "2": "Platform"
};
ReverseGlobals.ClientDeviceType = {
  "0": "Unknown",
  "1": "Xbox360",
  "2": "Playstation3",
  "3": "AndroidPhone",
  "4": "AndroidTablet",
  "5": "ApplePhone",
  "6": "AppleTablet",
  "7": "WebBrowser",
  "8": "NativeWindows",
  "9": "NativeMac",
  "10": "WindowsPhone",
  "11": "WindowsTablet",
  "12": "XboxOne",
  "13": "Playstation4",
  "255": "Fake"
};
ReverseGlobals.OptInFlags = {
  "1": "Newsletter",
  "2": "System",
  "4": "Marketing",
  "8": "UserResearch",
  "16": "CustomerService"
};
ReverseGlobals.EquipFailureReason = {
  "0": "None",
  "1": "ItemUnequippable",
  "2": "ItemUniqueEquipRestricted",
  "4": "ItemFailedUnlockCheck",
  "8": "ItemFailedLevelCheck",
  "16": "ItemNotOnCharacter"
};
ReverseGlobals.UnitType = {
  "0": "None",
  "1": "Count",
  "2": "PerGame",
  "3": "Seconds",
  "4": "Points",
  "5": "Team",
  "6": "Distance",
  "7": "Percent",
  "8": "Ratio",
  "9": "Boolean",
  "10": "WeaponType"
};
ReverseGlobals.EntityType = {
  "0": "None",
  "1": "User",
  "2": "Group",
  "3": "Post",
  "4": "Invitation",
  "5": "Report",
  "6": "Activity",
  "7": "Conversation"
};
ReverseGlobals.InvitationResponseState = {
  "0": "Unreviewed",
  "1": "Approved",
  "2": "Rejected"
};

exports.ReverseGlobals = ReverseGlobals;
exports.Globals = Globals;